# Generated by Django 5.0.1 on 2025-01-11 14:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Choices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now=True)),
                ('Updated_at', models.DateField(auto_now=True)),
                ('Choices', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now=True)),
                ('Updated_at', models.DateField(auto_now=True)),
                ('question', models.CharField(blank=True, max_length=200, null=True)),
                ('required', models.BooleanField(default=True)),
                ('question_type', models.CharField(blank=True, choices=[('LONG_ANSWER', 'LONG_ANSWER'), ('SHORT_ANSWER', 'SHORT_ANSWER'), ('MULTIPLE_CHOICE', 'MULTIPLE_CHOICE'), ('CHECK_BOX', 'CHECK_BOX')], null=True)),
                ('Choices', models.ManyToManyField(blank=True, related_name='question_choices', to='forms.choices')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Form',
            fields=[
                ('created_at', models.DateField(auto_now=True)),
                ('Updated_at', models.DateField(auto_now=True)),
                ('form_id', models.UUIDField(primary_key=True, serialize=False, verbose_name=uuid.uuid5)),
                ('form_name', models.CharField(blank=True, max_length=100, null=True)),
                ('bg_color', models.CharField(default='7FC6A4')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('questions', models.ManyToManyField(related_name='questions', to='forms.question')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
