# Generated by Django 5.0.1 on 2025-01-11 14:56

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choices',
            old_name='Choices',
            new_name='choices',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='Choices',
            new_name='choices',
        ),
        migrations.RemoveField(
            model_name='form',
            name='form_id',
        ),
        migrations.AddField(
            model_name='form',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='choices',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='form',
            name='bg_color',
            field=models.CharField(default='7FC6A4', max_length=7),
        ),
        migrations.AlterField(
            model_name='question',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
