# Generated by Django 5.0.1 on 2025-01-11 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0002_rename_choices_choices_choices_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='choices',
        ),
        migrations.RemoveField(
            model_name='form',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='form',
            name='questions',
        ),
        migrations.DeleteModel(
            name='Choices',
        ),
        migrations.DeleteModel(
            name='Form',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
