# Generated by Django 5.0.1 on 2025-01-11 15:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0004_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('created_at', models.DateField(auto_now=True)),
                ('Updated_at', models.DateField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('question', models.CharField(blank=True, max_length=200, null=True)),
                ('required', models.BooleanField(default=True)),
                ('question_type', models.CharField(blank=True, choices=[('LONG_ANSWER', 'LONG_ANSWER'), ('SHORT_ANSWER', 'SHORT_ANSWER'), ('MULTIPLE_CHOICE', 'MULTIPLE_CHOICE'), ('CHECK_BOX', 'CHECK_BOX')], null=True)),
                ('choices', models.ManyToManyField(blank=True, related_name='question_choices', to='forms.choices')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Form',
            fields=[
                ('created_at', models.DateField(auto_now=True)),
                ('Updated_at', models.DateField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('form_name', models.CharField(blank=True, max_length=100, null=True)),
                ('bg_color', models.CharField(default='7FC6A4', max_length=7)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('questions', models.ManyToManyField(related_name='questions', to='forms.question')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
