# Generated by Django 5.0.1 on 2025-01-14 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0002_table1'),
        ('forms', '0005_question_form'),
    ]

    operations = [
    ]
